# Generated by Django 4.2.11 on 2025-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transaction_options_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEH', 'Vehicles'), ('PROP', 'Property'), ('MOB', 'Mobiles & Tablets'), ('ELE', 'Electronics'), ('FUR', 'Furniture & Home Decor'), ('FAS', 'Fashion'), ('PET', 'Pets'), ('KID', 'Kids & Baby'), ('SPO', 'Sports & Outdoor'), ('BEA', 'Beauty & Personal Care'), ('HOB', 'Hobbies, Music, Books & Games'), ('BUS', 'Business & Industrial'), ('SER', 'Services'), ('JOB', 'Jobs'), ('OTH', 'Other')], max_length=50),
        ),
    ]
